plugin: aws_ec2
region: ap-northeast-2

# 어떤 서버들을 가져올지 필터링 (테라폼에서 설정한 태그 활용)
filters:
  instance-state-name: [ 'running' ]
  # 특정 프로젝트 태그가 있는 서버만 가져오기
  tag:Project: "SixSense" 

# 그룹 나누기 (예: bastion, web, db 등)
keyed_groups:
  - key: tags.Name
    separator: ""
    parent_group: "all_servers"

# 접속에 사용할 호스트 네임 설정 (Public IP 또는 Private IP)
hostnames:
  - ip-address        # Public IP 사용 시
  - private-ip-address # VPN이나 Bastion 통과 시

# SSH 접속 설정
compose:
  ansible_host: public_ip_address # 외부에서 접속할 때 기준
